sudo: false

git:
    depth: 1

language: php

php:
    - '7.2'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer self-update
    - composer install --prefer-source --ignore-platform-reqs

script:
    - vendor/bin/phpunit
